{% set name = "conda-docker" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda-incubator/conda-docker/archive/refs/tags/{{ version }}.tar.gz
  sha256: c7473bdc4368f23e6e4c2b3ea37c492ef9d88ee365616c4180f30ac898e82622

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - conda-docker=conda_docker.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - python-docker
    - conda
    - mamba
    - conda-standalone
    - fakechroot

test:
  imports:
    - conda_docker
  commands:
    - conda-docker --help

about:
  home: https://github.com/conda-incubator/conda-docker
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Create minimal docker images from conda environments
  description: |
    Conda Docker is an extension to the docker concept by having declarative
    environments that are associated with docker images. In addition this tool
    does not require docker to build images. Thus allowing for interesting
    caching behavior and tricks that docker would not normally allow.
  dev_url: https://github.com/conda-incubator/conda-docker

extra:
  recipe-maintainers:
    - costrouc
    - scopatz
