{% set name = "conda-docker" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/conda-docker/releases/download/{{ version }}/conda-docker-{{ version }}.tar.gz
  sha256: 17552de8a4c17372e79d660d23bdb7a992695d5202fe8975c886b1ebad37c574

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - conda-docker=conda_docker.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - conda
    - mamba
    - conda-standalone
    - fakechroot

test:
  imports:
    - conda_docker
  commands:
    - conda-docker --help

about:
  home: https://github.com/regro/conda-docker
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Create minimal docker images from conda environments
  description: |
    Conda Docker is an extension to the docker concept by having declarative
    environments that are associated with docker images. In addition this tool
    does not require docker to build images. Thus allowing for interesting
    caching behavior and tricks that docker would not normally allow.
  dev_url: https://github.com/regro/conda-docker

extra:
  recipe-maintainers:
    - costrouc
    - scopatz
